### ISSUE TITLE
[1.20.1-rc1] When relogging you appear below

### ISSUE THREAD

**Issue by muriplz** [MohistMC/Banner#60]
### Commit ID

b6aba84ffa4e90ab0cf1640c52441165f0e768dc

### Log with Error

no log

### Description of Error

when you quit the server and join back, your Y value gets decreased.

https://github.com/MohistMC/Banner/assets/46825658/f87e0750-97e2-4020-9f33-0d39bf409181

**Comment by RpeoCiv** [comment]
Hello,I ran into a similar problem,And I found the problem after trying.
modify file spigot.yml,And set setting:player-shuffle to 100
![image](https://github.com/MohistMC/Banner/assets/78863591/a866415b-adf6-4bd2-ba6f-b9e0d8d862ba)

**Comment by Zao-chen** [comment]
Yes,I have the same problem

**Comment by Zao-chen** [comment]
I have the same problem.I found out it should be a network related issue.
If your server and client are on the same computer, then this problem will not occur(you can help me to try it again)
If not, then this situation will occur.
I think the player entered the world before loading the world, and Free fall appeared.
The reason I came up with this is because I found if the player was flying, Y value doesn't get decreased.(ou can help me to try it again)
i use [114](https://github.com/MohistMC/Banner/actions/runs/5456008525)

**Comment by Geo3gamer** [comment]
bug is still present in build 260
